export const items = [
    {
        id: '1',
        name: 'Black Simple Lamp',
        category: 'popular',
        price: '$ 12.00',
        imgSrc: '/icons/blackSideLamp.svg',
        description: "A sleek and modern black lamp that fits perfectly on any desk or bedside table. Provides ample lighting while adding a touch of elegance to your space.",
    },
    {
        id: '2',
        name: 'Minimal Stand',
        category: 'popular',
        price: '$ 25.00',
        imgSrc: '/icons/minimalStand.svg',
        description: "A Minimal and functional stand designed to hold your devices or books. Its minimalistic design complements any modern decor.",
    },
    {
        id: '3',
        name: 'Coffee Chair',
        price: '$ 18.00',
        category: 'popular',
        imgSrc: '/icons/coffeChair.svg',
        description: "Comfortable and chic, this coffee chair is perfect for your living room or office. Its ergonomic design ensures maximum comfort.",
    },
    {
        id: '4',
        name: 'Simple Desk',
        price: '$ 15.00',
        category: 'popular',
        imgSrc: '/icons/simpleDesk.svg',
        description: "A compact and sturdy desk ideal for small spaces. Its simple design makes it a versatile addition to any room.",
    },
    {
        id: '5',
        name: 'chair 1',
        price: '$ 12.00',
        category: 'chair',
        imgSrc: '/icons/chair.jpg',
        description: "A classic chair that offers both comfort and style. Perfect for dining rooms, offices, or any seating area.",
    },
    {
        id: '6',
        name: 'table 1',
        price: '$ 8.00',
        category: 'table',
        imgSrc: '/icons/table.jpg',
        description: "A versatile table that can be used in various settings. Its sturdy construction ensures durability and long-lasting use.",
    },
    {
        id: '7',
        name: 'Arm Chair 1',
        price: '$ 28.00',
        category: 'armchair',
        imgSrc: '/icons/armChair.jpg',
        description: "An elegant armchair that provides exceptional comfort. Its stylish design makes it a great addition to any living space.",
    },
    {
        id: '8',
        name: 'bed 1',
        price: '$ 72.00',
        category: 'bed',
        imgSrc: '/icons/bed.jpg',
        description: "A comfortable and spacious bed that ensures a good night's sleep. Its modern design fits well with any bedroom decor.",
    },
];